esphome:
  name: example
  friendly_name: B Route Meter
  platformio_options:
    build_flags:
    - -std=gnu++17 -Wall -Wextra
    build_unflags:
    - -std=gnu++11
external_components:
#- source: 'components'
- source: github://homy-newfs8/esphome-broute@v0.1.1
  components: [ b_route ]

esp32:
  board: firebeetle32
  framework:
    #type: esp-idf
    type: arduino

logger:

api:
  password: !secret api_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_passphrase

ota:
  - platform: esphome
    password: !secret ota_password

uart:
  baud_rate: 115200
  rx_pin: 25
  tx_pin: 26
  # debug:
  #   sequence:
  #     - lambda: UARTDebug::log_string(direction, bytes);

b_route:
  rbid: !secret rb_id
  password: !secret rb_password
  power:
    name: power
    update_interval: 20s
    force_update: true
  energy:
    name: energy
    update_interval: 60s
    force_update: true
